/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: crittaa (https://sketchfab.com/crittaa)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/trivia-podium-316c947c0b54485bbd5edd29c73a6a00
title: Trivia Podium
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    TriviaBase_lambert2_0: THREE.Mesh
    TriviaButtonTrim_lambert5_0: THREE.Mesh
    TriviaButton1_lambert5_0: THREE.Mesh
    TriviaButton2_lambert4_0: THREE.Mesh
    TriviaButtonTrim2_lambert4_0: THREE.Mesh
    TriviaButton3_lambert6_0: THREE.Mesh
    TriviaButtonTrim3_lambert6_0: THREE.Mesh
    TriviaButton4_lambert7_0: THREE.Mesh
    TriviaButtonTrim4_lambert7_0: THREE.Mesh
  }
  materials: {
    lambert2: THREE.MeshStandardMaterial
    lambert5: THREE.MeshStandardMaterial
    lambert4: THREE.MeshStandardMaterial
    lambert6: THREE.MeshStandardMaterial
    lambert7: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/trivia.gltf') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[-1.22, 4, 0]} scale={[0.78, 1.17, 0.54]}>
            <mesh geometry={nodes.TriviaBase_lambert2_0.geometry} material={materials.lambert2} />
          </group>
          <group position={[-2.98, 7.78, -1]} rotation={[0, 0, -0.64]} scale={[0.51, 0.17, 0.59]}>
            <mesh
              geometry={nodes.TriviaButtonTrim_lambert5_0.geometry}
              material={nodes.TriviaButtonTrim_lambert5_0.material}
            />
          </group>
          <group position={[-2.98, 7.78, -1]} rotation={[0, 0, -0.64]} scale={[0.51, 0.17, 0.59]}>
            <mesh
              geometry={nodes.TriviaButton1_lambert5_0.geometry}
              material={nodes.TriviaButton1_lambert5_0.material}
            />
          </group>
          <group position={[-2.98, 7.78, 1]} rotation={[0, 0, -0.64]} scale={[0.51, 0.17, 0.59]}>
            <mesh
              geometry={nodes.TriviaButton2_lambert4_0.geometry}
              material={nodes.TriviaButton2_lambert4_0.material}
            />
          </group>
          <group position={[-2.98, 7.78, 1]} rotation={[0, 0, -0.64]} scale={[0.51, 0.17, 0.59]}>
            <mesh
              geometry={nodes.TriviaButtonTrim2_lambert4_0.geometry}
              material={nodes.TriviaButtonTrim2_lambert4_0.material}
            />
          </group>
          <group position={[-1, 6.31, 1]} rotation={[0, 0, -0.64]} scale={[0.51, 0.17, 0.59]}>
            <mesh
              geometry={nodes.TriviaButton3_lambert6_0.geometry}
              material={nodes.TriviaButton3_lambert6_0.material}
            />
          </group>
          <group position={[-1, 6.31, 1]} rotation={[0, 0, -0.64]} scale={[0.51, 0.17, 0.59]}>
            <mesh
              geometry={nodes.TriviaButtonTrim3_lambert6_0.geometry}
              material={nodes.TriviaButtonTrim3_lambert6_0.material}
            />
          </group>
          <group position={[-1, 6.31, -1]} rotation={[0, 0, -0.64]} scale={[0.51, 0.17, 0.59]}>
            <mesh
              geometry={nodes.TriviaButton4_lambert7_0.geometry}
              material={nodes.TriviaButton4_lambert7_0.material}
            />
          </group>
          <group position={[-1, 6.31, -1]} rotation={[0, 0, -0.64]} scale={[0.51, 0.17, 0.59]}>
            <mesh
              geometry={nodes.TriviaButtonTrim4_lambert7_0.geometry}
              material={nodes.TriviaButtonTrim4_lambert7_0.material}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/trivia.gltf')
