/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/scene2.gltf -o src/Modelo.tsx --types --keepnames 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['2_Drawer_Filing_Cabinet_2_Door_Filing_Container_0']: THREE.Mesh
    ['4_Drawer_Filing_Cabinet_4_Door_Filing_Container_0']: THREE.Mesh
    Back_Cushion_Office_Chair_0: THREE.Mesh
    Binders_Binders_0: THREE.Mesh
    Blade_Runner_Poster_Blade_Runner_Poster_0: THREE.Mesh
    Blank_Floppy_Disk_Blank_Floppy_Disk_0: THREE.Mesh
    ['Body_Panasonic_KX-T7420_0']: THREE.Mesh
    Bottle_Spray_Bottle_0: THREE.Mesh
    Bottom_Cushion_Office_Chair_0: THREE.Mesh
    Cabinet_Folder_Folder_0: THREE.Mesh
    Calculator_Calculator_0: THREE.Mesh
    Carpetimg_carpet_0: THREE.Mesh
    Clipboard_Clipboard_0: THREE.Mesh
    Computer_Monitor_PC_Monitor_amd_Keyboard_0: THREE.Mesh
    Corkboard_Corkboard_0: THREE.Mesh
    Cubicle_Cubicle_Wall_0: THREE.Mesh
    Cubicle_Desk_Desk_Legs_0: THREE.Mesh
    Cubicle_Desk_Desk_0: THREE.Mesh
    Cubicle_Trim_Cubicle_Trim_0: THREE.Mesh
    Doom_Floppy_Disk_Doom_Floppy_Disk_0: THREE.Mesh
    Drawer_4_Door_Filing_Container_0: THREE.Mesh
    Extension_Cable__0: THREE.Mesh
    Feather_Feather_0: THREE.Mesh
    FF7_Poster_256x256_FF7_Poster_256x256_0: THREE.Mesh
    Folder_Folder_0: THREE.Mesh
    Glowing_Screen_Screen_Emission_0: THREE.Mesh
    Handbook_for_the_Recently_Deceased_Handbook_for_the_Recently_De: THREE.Mesh
    Handbook_for_the_Recently_Deceased001_Material_0: THREE.Mesh
    Hang_In_There_Poster_Hang_In_There_0: THREE.Mesh
    hinge_Office_Chair_0: THREE.Mesh
    Keyboard_PC_Monitor_amd_Keyboard_0: THREE.Mesh
    mouse_PC_Tower_and_Mouse_0: THREE.Mesh
    Name_Plate_Name_Plate_0: THREE.Mesh
    Necronomicon_Necronomicon_0: THREE.Mesh
    NEWS_NEWS_0: THREE.Mesh
    Newspaper_Newspaper_0: THREE.Mesh
    Nintendo_Power_Vol_11_Nintendo_Power_Volume_11_0: THREE.Mesh
    Nintendo_Power_Vol_66_Nintendo_Power_Volume_11_0: THREE.Mesh
    Outlet_Power_Strip_0: THREE.Mesh
    Panasonic_VHS_TV_Panasonic_VHS_TV__0: THREE.Mesh
    PC_Tower_PC_Tower_and_Mouse_0: THREE.Mesh
    Pencil_Pencil_0: THREE.Mesh
    Pencil_2_Pencil_0: THREE.Mesh
    ['Phone_handle_Panasonic_KX-T7420_0']: THREE.Mesh
    Pin_Pin_Board_0: THREE.Mesh
    Piston_Office_Chair_0: THREE.Mesh
    Potted_Plant_Aglaonema_Leaf_0: THREE.Mesh
    Potted_Plant_Pot_Plant_0: THREE.Mesh
    Power_Cables_Power_Cable_0: THREE.Mesh
    Power_Plugs_Power_Cable_0: THREE.Mesh
    Rubiks_Cube_Rubiks_Cube_0: THREE.Mesh
    Secret_File_Stack_of_Papers_0: THREE.Mesh
    Shelf_Desk_0: THREE.Mesh
    Speed_Bus_Schedule_Speed_Bus_Schedule_0: THREE.Mesh
    Speed_VHS_Speed_VHS_0: THREE.Mesh
    Stapler_Swingline_Stapler_0: THREE.Mesh
    Sticky_Note_1001_Pin_Board_0: THREE.Mesh
    Sticky_Note_2_Pin_Board_0: THREE.Mesh
    Sticky_Notes_Stick_Notes_0: THREE.Mesh
    Terminator_Poster_Terminator_Poster_0: THREE.Mesh
    The_Box_The_box_0: THREE.Mesh
    Trash_Cam_Mesh_Basket_0: THREE.Mesh
    Tyler_Durden_Card_Business_Card_1_0: THREE.Mesh
    Umbrella_Corp_Key_Card_Umbrella_Corp_Key_Card_0: THREE.Mesh
    Unicorn_Origami_Unicorn_0: THREE.Mesh
    VHS_VHS_Tape_0: THREE.Mesh
    Wheels_Office_Chair_0: THREE.Mesh
    Y2K_Sticker_y2k_Sticker_0: THREE.Mesh
    Zeldas_Letter_Zeldas_Letter_0: THREE.Mesh
    Controller_Controller_0: THREE.Mesh
    Gc_GC_0: THREE.Mesh
    NEWS_NEWS_0001: THREE.Mesh
    Cube_Baked_Cube_Baked_0: THREE.Mesh
    Cube_Baked001_Cube_Baked_0: THREE.Mesh
    Cylinder_Material001_0: THREE.Mesh
    Cylinder_Material001_0001: THREE.Mesh
    NEWS_NEWS_0002: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_74: THREE.Mesh
    Object_76: THREE.Mesh
    Object_78: THREE.Mesh
    Object_80: THREE.Mesh
    Object_82: THREE.Mesh
    Object_4001: THREE.Mesh
    NEWS_NEWS_0003: THREE.Mesh
    Plane: THREE.Mesh
    Plane001: THREE.Mesh
    Plane002: THREE.Mesh
    Plane003: THREE.Mesh
    Plane004: THREE.Mesh
  }
  materials: {
    ['2_Door_Filing_Container']: THREE.MeshStandardMaterial
    ['4_Door_Filing_Container']: THREE.MeshStandardMaterial
    Office_Chair: THREE.MeshStandardMaterial
    Binders: THREE.MeshStandardMaterial
    Blade_Runner_Poster: THREE.MeshStandardMaterial
    Blank_Floppy_Disk: THREE.MeshStandardMaterial
    ['Panasonic_KX-T7420']: THREE.MeshStandardMaterial
    Spray_Bottle: THREE.MeshStandardMaterial
    Folder: THREE.MeshStandardMaterial
    Calculator: THREE.MeshStandardMaterial
    carpet: THREE.MeshStandardMaterial
    Clipboard: THREE.MeshStandardMaterial
    PC_Monitor_amd_Keyboard: THREE.MeshStandardMaterial
    Corkboard: THREE.MeshStandardMaterial
    Cubicle_Wall: THREE.MeshStandardMaterial
    Desk_Legs: THREE.MeshStandardMaterial
    Desk: THREE.MeshStandardMaterial
    Cubicle_Trim: THREE.MeshStandardMaterial
    Doom_Floppy_Disk: THREE.MeshStandardMaterial
    Extension_Cable__0: THREE.MeshStandardMaterial
    Feather: THREE.MeshStandardMaterial
    FF7_Poster_256x256: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    Handbook_for_the_Recently_Deceased: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    Hang_In_There: THREE.MeshStandardMaterial
    PC_Tower_and_Mouse: THREE.MeshStandardMaterial
    Name_Plate: THREE.MeshStandardMaterial
    Necronomicon: THREE.MeshStandardMaterial
    NEWS: THREE.MeshStandardMaterial
    Newspaper: THREE.MeshStandardMaterial
    Nintendo_Power_Volume_11: THREE.MeshStandardMaterial
    Power_Strip: THREE.MeshStandardMaterial
    Panasonic_VHS_TV: THREE.MeshStandardMaterial
    Pencil: THREE.MeshStandardMaterial
    Pin_Board: THREE.MeshStandardMaterial
    Aglaonema_Leaf: THREE.MeshStandardMaterial
    Pot_Plant: THREE.MeshStandardMaterial
    Power_Cable: THREE.MeshStandardMaterial
    Rubiks_Cube: THREE.MeshStandardMaterial
    ['Stack_of_Papers.001']: THREE.MeshStandardMaterial
    ['Desk.001']: THREE.MeshStandardMaterial
    Speed_Bus_Schedule: THREE.MeshStandardMaterial
    Speed_VHS: THREE.MeshStandardMaterial
    Swingline_Stapler: THREE.MeshStandardMaterial
    Stick_Notes: THREE.MeshStandardMaterial
    Terminator_Poster: THREE.MeshStandardMaterial
    The_box: THREE.MeshStandardMaterial
    Mesh_Basket: THREE.MeshStandardMaterial
    Business_Card_1: THREE.MeshStandardMaterial
    Umbrella_Corp_Key_Card: THREE.MeshStandardMaterial
    Origami_Unicorn: THREE.MeshStandardMaterial
    VHS_Tape: THREE.MeshStandardMaterial
    y2k_Sticker: THREE.MeshStandardMaterial
    Zeldas_Letter: THREE.MeshStandardMaterial
    Controller: THREE.MeshStandardMaterial
    ['material.001']: THREE.MeshStandardMaterial
    ['NEWS.002']: THREE.MeshStandardMaterial
    Cube_Baked: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['NEWS.003']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshPhysicalMaterial
    ['cover_back.007']: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    plastic_black: THREE.MeshStandardMaterial
    Plastic_transparent: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshStandardMaterial
    ['NEWS.004']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
    ['Material.014']: THREE.MeshStandardMaterial
  }
  animations: any[]
}

type ModelProps = JSX.IntrinsicElements['group'] & {
  visibleObjects?: Set<string>
}

export function Model({ visibleObjects, ...props }: ModelProps) {
  const { nodes, materials } = useGLTF('/scene2.gltf') as GLTFResult

  const isVisible = (name: string) => {
    if (!visibleObjects) return true
    return visibleObjects.has(name)
  }

  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_model002" position={[0, 0, 0.361]} rotation={[-Math.PI / 2, 0, 0]}>
        <group name="c7ca0b3869ba42d1ace1e163b90d388bfbx001" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="NEWS001" position={[-114.563, 105.62, -49.375]} rotation={[0, 1.571, 0]} scale={28}>
            <mesh name="NEWS_NEWS_0001" geometry={nodes.NEWS_NEWS_0001.geometry} material={materials['NEWS.002']} position={[-0.103, -0.058, -0.213]} rotation={[-Math.PI, 0.019, 0]} scale={[1, 0.559, 1]} />
          </group>
        </group>
      </group>
      <group name="Sketchfab_model003" position={[-1.055, 0.78, -0.246]} rotation={[-Math.PI / 2, 0, 0]} scale={0.638}>
        <group name="d436bddf16de402ebc2f385599331816fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh name="Cube_Baked_Cube_Baked_0" geometry={nodes.Cube_Baked_Cube_Baked_0.geometry} material={materials.Cube_Baked} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh name="Cube_Baked001_Cube_Baked_0" geometry={nodes.Cube_Baked001_Cube_Baked_0.geometry} material={materials.Cube_Baked} position={[1.247, 13.504, -1.032]} rotation={[-Math.PI, -0.567, -Math.PI / 2]} scale={100} />
        </group>
      </group>
      <group name="Sketchfab_model004" position={[-0.479, 0.801, -1.012]} rotation={[-Math.PI / 2, 0, 0]} scale={0.013}>
        <group name="c5e34776670946dd99777a8b5924366dfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="Cylinder" position={[-2.045, 230.542, -0.926]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh name="Cylinder_Material001_0" geometry={nodes.Cylinder_Material001_0.geometry} material={materials['Material.005']} position={[1.897, 0, 0.622]} rotation={[0, 0, -2.014]} />
          </group>
        </group>
      </group>
      <group name="Sketchfab_model005" position={[-0.365, 0.801, -0.979]} rotation={[-Math.PI / 2, 0, 0]} scale={0.013}>
        <group name="c5e34776670946dd99777a8b5924366dfbx001" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="Cylinder001" position={[-2.045, 230.542, -0.926]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh name="Cylinder_Material001_0001" geometry={nodes.Cylinder_Material001_0001.geometry} material={materials['Material.006']} position={[1.897, 0, 0.622]} rotation={[0, 0, -2.014]} />
          </group>
        </group>
      </group>
      <group name="Sketchfab_model006" position={[0, 0, -0.347]} rotation={[-Math.PI / 2, 0, 0]}>
        <group name="c7ca0b3869ba42d1ace1e163b90d388bfbx002" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="NEWS002" position={[-114.563, 105.62, -49.375]} rotation={[0, 1.571, 0]} scale={28}>
            <mesh name="NEWS_NEWS_0002" geometry={nodes.NEWS_NEWS_0002.geometry} material={materials['NEWS.003']} position={[1.121, 0.651, 3.38]} rotation={[-Math.PI, 1.542, 0]} />
          </group>
        </group>
      </group>
      <group name="Sketchfab_model007" position={[-1.03, 1.373, 0]} rotation={[-Math.PI / 2, 0, 1.405]} scale={0.065}>
        <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
          <group name="Plane_0" rotation={[1.456, 0, 0]}>
            <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials['Material.008']} position={[4.568, -1.336, 0.802]} scale={1.372} />
            <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials['Material.009']} />
          </group>
        </group>
      </group>
      <group name="Sketchfab_model008" position={[-1.235, 1.278, -0.013]} rotation={[-Math.PI / 2, 0, 1.752]}>
        <group name="GLTF_SceneRootNode001" rotation={[Math.PI / 2, 0, 0]}>
          <group name="CD_CASE007_42" position={[-0.34, 0.062, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
            <group name="cover_front007_38" position={[4.449, 6.913, -1.006]} rotation={[0, 0, -Math.PI / 2]} scale={1000}>
              <mesh name="Object_76" geometry={nodes.Object_76.geometry} material={materials['Material.011']} rotation={[3.13, 0, 0]} />
            </group>
            <mesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials['cover_back.007']} position={[0, -19.912, -53.053]} scale={1000} />
            <mesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials.plastic_black} position={[0, -19.912, -53.053]} scale={1000} />
            <mesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials.Plastic_transparent} position={[0.065, -19.912, -53.053]} scale={1000} />
            <mesh name="Object_82" geometry={nodes.Object_82.geometry} material={materials.Plastic_transparent} position={[18.96, 4.347, -0.332]} rotation={[0, 0, -Math.PI / 2]} scale={1000} />
          </group>
        </group>
      </group>
      <group name="Sketchfab_model009" position={[0.101, 1.228, -0.745]} rotation={[-Math.PI / 2, 0, -0.341]} scale={0.065}>
        <group name="GLTF_SceneRootNode002" rotation={[Math.PI / 2, 0, 0]}>
          <group name="Plane_0001" rotation={[1.456, 0, 0]}>
            <mesh name="Object_4001" geometry={nodes.Object_4001.geometry} material={materials['Material.012']} position={[4.568, -1.336, 0.802]} scale={1.372} />
          </group>
        </group>
      </group>
      <group name="Sketchfab_model010" position={[0.242, 0, -0.347]} rotation={[-Math.PI / 2, 0, 0]}>
        <group name="c7ca0b3869ba42d1ace1e163b90d388bfbx003" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="NEWS003" position={[-114.563, 105.62, -49.375]} rotation={[0, 1.571, 0]} scale={28}>
            <mesh name="NEWS_NEWS_0003" geometry={nodes.NEWS_NEWS_0003.geometry} material={materials['NEWS.004']} position={[1.121, 0.977, 3.487]} rotation={[-Math.PI, 1.542, 0]} scale={[1.187, 0.593, 1]} />
          </group>
        </group>
      </group>
      <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.003']} position={[0.618, 0.989, 1.17]} rotation={[Math.PI / 2, 0, 0]} scale={[0.284, 1, 0.519]} />
      <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Material.004']} position={[-0.088, 0.883, 1.17]} rotation={[Math.PI / 2, 0, 0]} scale={[0.291, 1, 0.427]} />
      <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials['Material.010']} position={[-1.052, 1.336, -0.305]} rotation={[1.527, 0.248, -1.387]} scale={[0.077, 0.263, 0.047]} />
      <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials['Material.013']} position={[0.407, 1.196, -0.717]} rotation={[1.333, -0.082, 0.333]} scale={[0.077, 0.263, 0.047]} />
      <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={materials['Material.014']} position={[1.161, 0.989, -0.755]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.284, 1, 0.519]} />
      <group name="c7ca0b3869ba42d1ace1e163b90d388bfbx" scale={0.01}>
        <group name="Blade_Runner_Poster" position={[116.67, 97.534, -76.631]} rotation={[0.07, Math.PI / 2, 0]} scale={[104, 104, 0]} visible={isVisible('Blade_Runner_Poster')}>
          <mesh name="Blade_Runner_Poster_Blade_Runner_Poster_0" geometry={nodes.Blade_Runner_Poster_Blade_Runner_Poster_0.geometry} material={materials.Blade_Runner_Poster} position={[0, 0, 0.983]} />
        </group>
        <group name="Cubicle_Desk" position={[-57.792, 59.982, -11.777]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} visible={isVisible('Cubicle_Desk')}>
          <mesh name="Cubicle_Desk_Desk_Legs_0" geometry={nodes.Cubicle_Desk_Desk_Legs_0.geometry} material={materials.Desk_Legs} />
          <mesh name="Cubicle_Desk_Desk_0" geometry={nodes.Cubicle_Desk_Desk_0.geometry} material={materials.Desk} />
        </group>
        <group name="Glowing_Screen" position={[-77.692, 107.123, -74.439]} rotation={[0, Math.PI / 4, 0]} scale={15.008} visible={isVisible('Glowing_Screen')}>
          <mesh name="Glowing_Screen_Screen_Emission_0" geometry={nodes.Glowing_Screen_Screen_Emission_0.geometry} material={materials['Material.007']} rotation={[Math.PI, -0.001, Math.PI]} />
        </group>
        <group name="Potted_Plant" position={[52.952, 137.716, -94.981]} rotation={[-Math.PI / 2, 0, 0.436]} scale={19.5} visible={isVisible('Potted_Plant')}>
          <mesh name="Potted_Plant_Aglaonema_Leaf_0" geometry={nodes.Potted_Plant_Aglaonema_Leaf_0.geometry} material={materials.Aglaonema_Leaf} />
          <mesh name="Potted_Plant_Pot_Plant_0" geometry={nodes.Potted_Plant_Pot_Plant_0.geometry} material={materials.Pot_Plant} />
        </group>
        <group name="Terminator_Poster" position={[61.222, 100.976, 117.201]} rotation={[-Math.PI, 0, -3.122]} scale={[80, 80, 0]} visible={isVisible('Terminator_Poster')}>
          <mesh name="Terminator_Poster_Terminator_Poster_0" geometry={nodes.Terminator_Poster_Terminator_Poster_0.geometry} material={materials.Terminator_Poster} position={[0, 0, -0.57]} />
        </group>
        <mesh name="2_Drawer_Filing_Cabinet_2_Door_Filing_Container_0" geometry={nodes['2_Drawer_Filing_Cabinet_2_Door_Filing_Container_0'].geometry} material={materials['2_Door_Filing_Container']} position={[-86.3, 35.988, 87.741]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh name="4_Drawer_Filing_Cabinet_4_Door_Filing_Container_0" geometry={nodes['4_Drawer_Filing_Cabinet_4_Door_Filing_Container_0'].geometry} material={materials['4_Door_Filing_Container']} position={[47.572, 56.699, -87.941]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh name="Back_Cushion_Office_Chair_0" geometry={nodes.Back_Cushion_Office_Chair_0.geometry} material={materials.Office_Chair} position={[21.317, 82.072, 6.475]} rotation={[-2.99, -0.955, -1.185]} scale={100} />
        <mesh name="Binders_Binders_0" geometry={nodes.Binders_Binders_0.geometry} material={materials.Binders} position={[-108.714, 135.48, -14.509]} rotation={[-Math.PI / 2, 0, 0]} scale={[8.654, 1.912, 11.745]} />
        <mesh name="Blank_Floppy_Disk_Blank_Floppy_Disk_0" geometry={nodes.Blank_Floppy_Disk_Blank_Floppy_Disk_0.geometry} material={materials.Blank_Floppy_Disk} position={[-102.485, 74.92, -51.614]} rotation={[-Math.PI / 2, 0, 0.262]} scale={17.794} />
        <mesh name="Body_Panasonic_KX-T7420_0" geometry={nodes['Body_Panasonic_KX-T7420_0'].geometry} material={materials['Panasonic_KX-T7420']} position={[11.189, 76.227, -97.201]} rotation={[-Math.PI / 2, 0, -1.745]} scale={8.002} />
        <mesh name="Bottle_Spray_Bottle_0" geometry={nodes.Bottle_Spray_Bottle_0.geometry} material={materials.Spray_Bottle} position={[56.98, 128.551, -74.317]} rotation={[-Math.PI / 2, 0, Math.PI / 4]} scale={2.24} />
        <mesh name="Bottom_Cushion_Office_Chair_0" geometry={nodes.Bottom_Cushion_Office_Chair_0.geometry} material={materials.Office_Chair} position={[-1.062, 46.877, -9.195]} rotation={[-Math.PI / 2, 0, -Math.PI / 9]} scale={100} />
        <mesh name="Cabinet_Folder_Folder_0" geometry={nodes.Cabinet_Folder_Folder_0.geometry} material={materials.Folder} position={[49.808, 42.008, -63.39]} rotation={[-Math.PI, 0, -1.597]} scale={21.396} />
        <mesh name="Calculator_Calculator_0" geometry={nodes.Calculator_Calculator_0.geometry} material={materials.Calculator} position={[-44.297, 45.597, -86.92]} rotation={[-Math.PI / 2, 0, -Math.PI / 6]} scale={3.281} />
        <mesh name="Carpetimg_carpet_0" geometry={nodes.Carpetimg_carpet_0.geometry} material={materials.carpet} position={[0, 0, 3.835]} rotation={[-Math.PI / 2, 0, 0]} scale={240} />
        <mesh name="Clipboard_Clipboard_0" geometry={nodes.Clipboard_Clipboard_0.geometry} material={materials.Clipboard} position={[99.688, 0.318, -23.566]} rotation={[-Math.PI / 2, 0, 0.698]} scale={[8.027, 10.327, 10.327]} />
        <mesh name="Computer_Monitor_PC_Monitor_amd_Keyboard_0" geometry={nodes.Computer_Monitor_PC_Monitor_amd_Keyboard_0.geometry} material={materials.PC_Monitor_amd_Keyboard} position={[-90.028, 99.752, -86.591]} rotation={[-Math.PI / 2, 0, -Math.PI / 4]} scale={[15.893, 17.778, 17.778]} visible={isVisible('Computer_Monitor')} />
        <mesh name="Corkboard_Corkboard_0" geometry={nodes.Corkboard_Corkboard_0.geometry} material={materials.Corkboard} position={[-17.879, 125.627, -114.356]} rotation={[-Math.PI / 2, 0, 0]} scale={4} />
        <mesh name="Cubicle_Cubicle_Wall_0" geometry={nodes.Cubicle_Cubicle_Wall_0.geometry} material={materials.Cubicle_Wall} position={[-16.93, 84.399, -6.542]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
        <mesh name="Cubicle_Trim_Cubicle_Trim_0" geometry={nodes.Cubicle_Trim_Cubicle_Trim_0.geometry} material={materials.Cubicle_Trim} position={[-16.376, 84.898, -4.593]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
        <mesh name="Doom_Floppy_Disk_Doom_Floppy_Disk_0" geometry={nodes.Doom_Floppy_Disk_Doom_Floppy_Disk_0.geometry} material={materials.Doom_Floppy_Disk} position={[-41.908, 45.024, -73.756]} rotation={[-Math.PI / 2, 0, -1.92]} scale={17.794} />
        <mesh name="Drawer_4_Door_Filing_Container_0" geometry={nodes.Drawer_4_Door_Filing_Container_0.geometry} material={materials['4_Door_Filing_Container']} position={[47.549, 37.984, -57.33]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh name="Extension_Cable__0" geometry={nodes.Extension_Cable__0.geometry} material={materials.Extension_Cable__0} position={[-103.435, 41.242, -14.317]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh name="Feather_Feather_0" geometry={nodes.Feather_Feather_0.geometry} material={materials.Feather} position={[46.951, 113.595, -74.514]} rotation={[-Math.PI / 2, 0, -0.698]} scale={8} />
        <mesh name="FF7_Poster_256x256_FF7_Poster_256x256_0" geometry={nodes.FF7_Poster_256x256_FF7_Poster_256x256_0.geometry} material={materials.FF7_Poster_256x256} position={[-8.813, 91.17, 116.981]} rotation={[Math.PI, 0, Math.PI]} scale={80} />
        <mesh name="Folder_Folder_0" geometry={nodes.Folder_Folder_0.geometry} material={materials.Folder} position={[-79.872, 0.567, 47.001]} rotation={[-Math.PI / 2, 0, -0.934]} scale={21.396} />
        <mesh name="Handbook_for_the_Recently_Deceased_Handbook_for_the_Recently_De" geometry={nodes.Handbook_for_the_Recently_Deceased_Handbook_for_the_Recently_De.geometry} material={materials.Handbook_for_the_Recently_Deceased} position={[-108.088, 138.496, 0]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[8.4, 1.4, 7]} />
        <mesh name="Handbook_for_the_Recently_Deceased001_Material_0" geometry={nodes.Handbook_for_the_Recently_Deceased001_Material_0.geometry} material={materials['Material.001']} position={[-108.088, 138.496, 13.437]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[8.4, 1.4, 7]} />
        <mesh name="Hang_In_There_Poster_Hang_In_There_0" geometry={nodes.Hang_In_There_Poster_Hang_In_There_0.geometry} material={materials.Hang_In_There} position={[93.658, 106.168, -114.384]} scale={50} />
        <mesh name="hinge_Office_Chair_0" geometry={nodes.hinge_Office_Chair_0.geometry} material={materials.Office_Chair} position={[17.445, 47.559, 3.764]} rotation={[-Math.PI / 2, 0, -0.611]} scale={0.92} />
        <mesh name="Keyboard_PC_Monitor_amd_Keyboard_0" geometry={nodes.Keyboard_PC_Monitor_amd_Keyboard_0.geometry} material={materials.PC_Monitor_amd_Keyboard} position={[-67.841, 76.211, -55.377]} rotation={[-Math.PI / 2, 0, 0.885]} scale={39.493} visible={isVisible('Keyboard')} />
        <mesh name="mouse_PC_Tower_and_Mouse_0" geometry={nodes.mouse_PC_Tower_and_Mouse_0.geometry} material={materials.PC_Tower_and_Mouse} position={[-40.755, 75.536, -75.159]} rotation={[-Math.PI / 2, 0, -0.96]} scale={30.894} visible={isVisible('mouse')} />
        <mesh name="Name_Plate_Name_Plate_0" geometry={nodes.Name_Plate_Name_Plate_0.geometry} material={materials.Name_Plate} position={[120.605, 156.222, -24.97]} rotation={[0, 1.571, 0]} scale={9.52} />
        <mesh name="Necronomicon_Necronomicon_0" geometry={nodes.Necronomicon_Necronomicon_0.geometry} material={materials.Necronomicon} position={[98.75, 9.706, -81.582]} rotation={[-0.051, 0.19, 0.971]} scale={[8.4, 1.4, 7]} />
        <mesh name="NEWS_NEWS_0" geometry={nodes.NEWS_NEWS_0.geometry} material={materials.NEWS} position={[-114.563, 105.62, -49.375]} rotation={[0, 1.571, 0]} scale={28} />
        <mesh name="Newspaper_Newspaper_0" geometry={nodes.Newspaper_Newspaper_0.geometry} material={materials.Newspaper} position={[90.845, 1.074, -39.379]} rotation={[-Math.PI / 2, 0, -Math.PI / 9]} scale={52} />
        <mesh name="Nintendo_Power_Vol_11_Nintendo_Power_Volume_11_0" geometry={nodes.Nintendo_Power_Vol_11_Nintendo_Power_Volume_11_0.geometry} material={materials.Nintendo_Power_Volume_11} position={[5.875, 76.206, -70.894]} rotation={[-Math.PI / 2, 0, -2.094]} scale={[19.173, 19.173, 1.554]} />
        <mesh name="Nintendo_Power_Vol_66_Nintendo_Power_Volume_11_0" geometry={nodes.Nintendo_Power_Vol_66_Nintendo_Power_Volume_11_0.geometry} material={materials.Nintendo_Power_Volume_11} position={[-3.255, 76.364, -69.664]} rotation={[-Math.PI / 2, 0, -1.745]} scale={[19.173, 19.173, 1.554]} />
        <mesh name="Outlet_Power_Strip_0" geometry={nodes.Outlet_Power_Strip_0.geometry} material={materials.Power_Strip} position={[-107.974, 2.241, -3.593]} rotation={[-Math.PI / 2, 0, -1.745]} scale={[-18, -3.6, -2.24]} />
        <mesh name="Panasonic_VHS_TV_Panasonic_VHS_TV__0" geometry={nodes.Panasonic_VHS_TV_Panasonic_VHS_TV__0.geometry} material={materials.Panasonic_VHS_TV} position={[-87.033, 98.636, 89.158]} rotation={[-Math.PI / 2, 0, 0.611]} scale={24.7} />
        <mesh name="PC_Tower_PC_Tower_and_Mouse_0" geometry={nodes.PC_Tower_PC_Tower_and_Mouse_0.geometry} material={materials.PC_Tower_and_Mouse} position={[-43.457, 22.5, -83.956]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
        <mesh name="Pencil_Pencil_0" geometry={nodes.Pencil_Pencil_0.geometry} material={materials.Pencil} position={[-78.253, 75.169, 16.654]} rotation={[-Math.PI / 2, 0, -0.262]} scale={0.407} />
        <mesh name="Pencil_2_Pencil_0" geometry={nodes.Pencil_2_Pencil_0.geometry} material={materials.Pencil} position={[-81.507, 75.038, -74.836]} rotation={[-Math.PI / 2, 0, -1.134]} scale={100} />
        <mesh name="Phone_handle_Panasonic_KX-T7420_0" geometry={nodes['Phone_handle_Panasonic_KX-T7420_0'].geometry} material={materials['Panasonic_KX-T7420']} position={[6.188, 78.276, -97.751]} rotation={[-1.485, -0.015, -1.745]} scale={19.379} />
        <mesh name="Pin_Pin_Board_0" geometry={nodes.Pin_Pin_Board_0.geometry} material={materials.Pin_Board} position={[-38.278, 131.347, -37.142]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={-3.201} />
        <mesh name="Piston_Office_Chair_0" geometry={nodes.Piston_Office_Chair_0.geometry} material={materials.Office_Chair} position={[2.183, 37.137, -6.923]} rotation={[-Math.PI / 2, 0, -0.611]} scale={9.784} />
        <mesh name="Power_Cables_Power_Cable_0" geometry={nodes.Power_Cables_Power_Cable_0.geometry} material={materials.Power_Cable} position={[-103.435, 41.242, -14.317]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh name="Power_Plugs_Power_Cable_0" geometry={nodes.Power_Plugs_Power_Cable_0.geometry} material={materials.Power_Cable} position={[-107.081, 5.749, 3.222]} rotation={[-Math.PI / 2, 0, 0]} scale={10} />
        <mesh name="Rubiks_Cube_Rubiks_Cube_0" geometry={nodes.Rubiks_Cube_Rubiks_Cube_0.geometry} material={materials.Rubiks_Cube} position={[-100.925, 77.556, -36.815]} rotation={[-Math.PI / 2, 0, -0.436]} scale={4.569} visible={isVisible('Rubiks_Cube')} />
        <mesh name="Secret_File_Stack_of_Papers_0" geometry={nodes.Secret_File_Stack_of_Papers_0.geometry} material={materials['Stack_of_Papers.001']} position={[48.564, 30.157, -68.13]} rotation={[-Math.PI / 2, 0, 0]} scale={[10.795, 13.97, 10.594]} />
        <mesh name="Shelf_Desk_0" geometry={nodes.Shelf_Desk_0.geometry} material={materials['Desk.001']} position={[-110.254, 126.246, -2.482]} rotation={[-Math.PI / 2, 0, 0]} scale={[8.973, 44.467, 1.666]} />
        <mesh name="Speed_Bus_Schedule_Speed_Bus_Schedule_0" geometry={nodes.Speed_Bus_Schedule_Speed_Bus_Schedule_0.geometry} material={materials.Speed_Bus_Schedule} position={[-71.684, 124.496, 96.575]} rotation={[-Math.PI / 2, 0, -2.967]} scale={30.25} />
        <mesh name="Speed_VHS_Speed_VHS_0" geometry={nodes.Speed_VHS_Speed_VHS_0.geometry} material={materials.Speed_VHS} position={[-83.323, 127.987, 82.693]} rotation={[-Math.PI / 2, 0, 2.922]} scale={10.114} />
        <mesh name="Stapler_Swingline_Stapler_0" geometry={nodes.Stapler_Swingline_Stapler_0.geometry} material={materials.Swingline_Stapler} position={[-56.124, 75.564, -93.7]} rotation={[-Math.PI / 2, 0, 0.873]} scale={[6.648, 1.108, 0.665]} />
        <mesh name="Sticky_Note_1001_Pin_Board_0" geometry={nodes.Sticky_Note_1001_Pin_Board_0.geometry} material={materials.Pin_Board} position={[-119.23, 107.379, 23.182]} rotation={[-Math.PI, 0, -Math.PI]} scale={12.555} />
        <mesh name="Sticky_Note_2_Pin_Board_0" geometry={nodes.Sticky_Note_2_Pin_Board_0.geometry} material={materials.Pin_Board} position={[-13.031, 111.501, -113.314]} rotation={[0, 1.571, 0]} scale={12.555} />
        <mesh name="Sticky_Notes_Stick_Notes_0" geometry={nodes.Sticky_Notes_Stick_Notes_0.geometry} material={materials.Stick_Notes} position={[-79.498, 112.216, -71.829]} rotation={[0, Math.PI / 4, -2.007]} scale={4.728} />
        <mesh name="The_Box_The_box_0" geometry={nodes.The_Box_The_box_0.geometry} material={materials.The_box} position={[-0.368, 12.087, -91.609]} rotation={[Math.PI, 0.436, 0]} scale={100} />
        <mesh name="Trash_Cam_Mesh_Basket_0" geometry={nodes.Trash_Cam_Mesh_Basket_0.geometry} material={materials.Mesh_Basket} position={[92.205, 21.872, -78.119]} rotation={[-Math.PI / 2, 0, 0]} scale={17.532} />
        <mesh name="Tyler_Durden_Card_Business_Card_1_0" geometry={nodes.Tyler_Durden_Card_Business_Card_1_0.geometry} material={materials.Business_Card_1} position={[-2.996, 75.267, -94.903]} rotation={[-Math.PI / 2, 0, Math.PI / 9]} scale={[3.072, 1.92, 1.92]} />
        <mesh name="Umbrella_Corp_Key_Card_Umbrella_Corp_Key_Card_0" geometry={nodes.Umbrella_Corp_Key_Card_Umbrella_Corp_Key_Card_0.geometry} material={materials.Umbrella_Corp_Key_Card} position={[40.698, 30.658, -58.756]} rotation={[-Math.PI / 2, 0, -0.96]} scale={10} />
        <mesh name="Unicorn_Origami_Unicorn_0" geometry={nodes.Unicorn_Origami_Unicorn_0.geometry} material={materials.Origami_Unicorn} position={[-90.219, 128.501, 67.792]} rotation={[-Math.PI, 0.436, Math.PI / 2]} scale={1.2} />
        <mesh name="VHS_VHS_Tape_0" geometry={nodes.VHS_VHS_Tape_0.geometry} material={materials.VHS_Tape} position={[-83.312, 125.471, 81.68]} rotation={[-Math.PI / 2, 0, -2.967]} scale={10.114} />
        <mesh name="Wheels_Office_Chair_0" geometry={nodes.Wheels_Office_Chair_0.geometry} material={materials.Office_Chair} position={[1.972, 9.119, -7.071]} rotation={[0, -0.611, -1.92]} scale={[-8.114, -8.114, -3.083]} />
        <mesh name="Y2K_Sticker_y2k_Sticker_0" geometry={nodes.Y2K_Sticker_y2k_Sticker_0.geometry} material={materials.y2k_Sticker} position={[-33.056, 26.249, -82.059]} rotation={[-0.262, Math.PI / 2, 0]} scale={6} />
        <mesh name="Zeldas_Letter_Zeldas_Letter_0" geometry={nodes.Zeldas_Letter_Zeldas_Letter_0.geometry} material={materials.Zeldas_Letter} position={[-118.102, 102.655, 52.571]} rotation={[-1.484, 0, 0]} scale={100} />
      </group>
      <group name="Controller001" position={[-0.153, -0.35, 1.401]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh name="Controller_Controller_0" geometry={nodes.Controller_Controller_0.geometry} material={materials.Controller} position={[-0.866, 0.93, 1.177]} rotation={[0, 0, 1.738]} scale={0.359} />
      </group>
      <group name="Gc" position={[-0.153, -0.35, 1.401]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh name="Gc_GC_0" geometry={nodes.Gc_GC_0.geometry} material={materials['material.001']} position={[-0.843, 0.94, 1.176]} rotation={[0, 0, 1.631]} scale={0.348} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene2.gltf')
