/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: NobleCrow (https://sketchfab.com/NobleCrow)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/low-poly-90s-office-cubicle-4912ac8a39e546e39524badcca7b240f
title: Low Poly 90s Office Cubicle
*/

import * as THREE from 'three'
import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

type GLTFResult = {
  nodes: {
    ['Phonehandle_Panasonic_KX-T7420_0']: THREE.Mesh
    ['Body_Panasonic_KX-T7420_0']: THREE.Mesh
    Wheels_Office_Chair_0: THREE.Mesh
    Piston_Office_Chair_0: THREE.Mesh
    Bottom_Cushion_Office_Chair_0: THREE.Mesh
    Back_Cushion_Office_Chair_0: THREE.Mesh
    hinge_Office_Chair_0: THREE.Mesh
    Controller_N64_Controller_0: THREE.Mesh
    Power_Plugs_Power_Cable_0: THREE.Mesh
    Power_Cables_Power_Cable_0: THREE.Mesh
    Extension_Cable__0: THREE.Mesh
    Handbook_for_the_Recently_Deceased_Handbook_for_the_Recently_Deceased_0: THREE.Mesh
    Necronomicon_Necronomicon_0: THREE.Mesh
    Binders_Binders_0: THREE.Mesh
    Sticky_Notes_Stick_Notes_0: THREE.Mesh
    CD_CD_Case_0: THREE.Mesh
    CD_CD_0: THREE.Mesh
    Nevermind_CD_Nevermind_CD_0: THREE.Mesh
    Ten_CD_Ten_CD_0: THREE.Mesh
    Definitely_Maybe_CD_Definitely_Maybe_CD_0: THREE.Mesh
    Astro_Lounge_CD_Astro_Lounge_CD_0: THREE.Mesh
    Handbook_for_the_Recently_Deceased001_Material_0: THREE.Mesh
    Burger_Burger_0: THREE.Mesh
    Burger_Bag_Bag_0: THREE.Mesh
    Wrapper_Wrapper_0: THREE.Mesh
    Y2K_Sticker_y2k_Sticker_0: THREE.Mesh
    Hang_In_There_Poster_Hang_In_There_0: THREE.Mesh
    The_Box_The_box_0: THREE.Mesh
    Potted_Plant_Pot_Plant_0: THREE.Mesh
    Potted_Plant_Aglaonema_Leaf_0: THREE.Mesh
    Bottle_Spray_Bottle_0: THREE.Mesh
    PC_Tower_PC_Tower_and_Mouse_0: THREE.Mesh
    mouse_PC_Tower_and_Mouse_0: THREE.Mesh
    Keyboard_PC_Monitor_amd_Keyboard_0: THREE.Mesh
    Computer_Monitor_PC_Monitor_amd_Keyboard_0: THREE.Mesh
    ['2_Drawer_Filing_Cabinet_2_Door_Filing_Container_0']: THREE.Mesh
    Pencil_Pencil_0: THREE.Mesh
    Pencil_2_Pencil_0: THREE.Mesh
    Clipboard_Clipboard_0: THREE.Mesh
    Drawer_4_Door_Filing_Container_0: THREE.Mesh
    Calculator_Calculator_0: THREE.Mesh
    VHS_VHS_Tape_0: THREE.Mesh
    Blank_Floppy_Disk_Blank_Floppy_Disk_0: THREE.Mesh
    Doom_Floppy_Disk_Doom_Floppy_Disk_0: THREE.Mesh
    Cubicle_Desk_Desk_0: THREE.Mesh
    Cubicle_Desk_Desk_Legs_0: THREE.Mesh
    ['4_Drawer_Filing_Cabinet_4_Door_Filing_Container_0']: THREE.Mesh
    Cubicle_Cubicle_Wall_0: THREE.Mesh
    Cubicle_Trim_Cubicle_Trim_0: THREE.Mesh
    Folder_Folder_0: THREE.Mesh
    Stack_of_Papers_Stack_of_Papers_0: THREE.Mesh
    Secret_File_Stack_of_Papers_0: THREE.Mesh
    Cabinet_Folder_Folder_0: THREE.Mesh
    Corkboard_Corkboard_0: THREE.Mesh
    Pin_Pin_Board_0: THREE.Mesh
    Sticky_Note_1_Pin_Board_0: THREE.Mesh
    Sticky_Note_2_Pin_Board_0: THREE.Mesh
    Rubiks_Cube_Rubiks_Cube_0: THREE.Mesh
    Nintendo_Power_Vol_11_Nintendo_Power_Volume_11_0: THREE.Mesh
    Nintendo_Power_Vol_66_Nintendo_Power_Volume_11_0: THREE.Mesh
    Nirvana_Calendar_Nirvana_Calendar_0: THREE.Mesh
    Blade_Runner_Poster_Blade_Runner_Poster_0: THREE.Mesh
    Coffee_Cup_Coffee_Cup_0: THREE.Mesh
    Steam_Steam_0: THREE.Mesh
    Terminator_Poster_Terminator_Poster_0: THREE.Mesh
    Panasonic_VHS_TV_Panasonic_VHS_TV__0: THREE.Mesh
    N64_Console_Nintendo_64_0: THREE.Mesh
    Carpetimg_carpet_0: THREE.Mesh
    Outlet_Power_Strip_0: THREE.Mesh
    Trash_Cam_Mesh_Basket_0: THREE.Mesh
    Speed_VHS_Speed_VHS_0: THREE.Mesh
    Super_Mario_64_Cartridge_Super_Mario_64_Cartridge_0: THREE.Mesh
    Shelf_Desk_0: THREE.Mesh
    Stapler_Swingline_Stapler_0: THREE.Mesh
    Tyler_Durden_Card_Business_Card_1_0: THREE.Mesh
    Name_Plate_Name_Plate_0: THREE.Mesh
    Sticky_Note_1001_Pin_Board_0: THREE.Mesh
    Fallout_2_Game_Box_256x256_Fallout_2_Game_Box_256x256_0: THREE.Mesh
    Half_Life_Game_Box_256x256_Half_Life_Game_Box_256x256_0: THREE.Mesh
    Speed_Bus_Schedule_Speed_Bus_Schedule_0: THREE.Mesh
    NEWS_NEWS_0: THREE.Mesh
    Newspaper_Newspaper_0: THREE.Mesh
    Notepad__Notepad__0: THREE.Mesh
    Feather_Feather_0: THREE.Mesh
    Umbrella_Corp_Key_Card_Umbrella_Corp_Key_Card_0: THREE.Mesh
    Unicorn_Origami_Unicorn_0: THREE.Mesh
    FF7_Poster_256x256_FF7_Poster_256x256_0: THREE.Mesh
    Glowing_Screen_Screen_Emission_0: THREE.Mesh
    Zeldas_Letter_Zeldas_Letter_0: THREE.Mesh
  }
  materials: {
    ['Panasonic_KX-T7420']: THREE.MeshStandardMaterial
    Office_Chair: THREE.MeshStandardMaterial
    N64_Controller: THREE.MeshStandardMaterial
    Power_Cable: THREE.MeshStandardMaterial
    Extension_Cable__0: THREE.MeshStandardMaterial
    Handbook_for_the_Recently_Deceased: THREE.MeshStandardMaterial
    Necronomicon: THREE.MeshStandardMaterial
    Binders: THREE.MeshStandardMaterial
    Stick_Notes: THREE.MeshStandardMaterial
    CD_Case: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    Nevermind_CD: THREE.MeshStandardMaterial
    Ten_CD: THREE.MeshStandardMaterial
    Definitely_Maybe_CD: THREE.MeshStandardMaterial
    Astro_Lounge_CD: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    Burger: THREE.MeshStandardMaterial
    material_17: THREE.MeshStandardMaterial
    Wrapper: THREE.MeshStandardMaterial
    y2k_Sticker: THREE.MeshStandardMaterial
    Hang_In_There: THREE.MeshStandardMaterial
    The_box: THREE.MeshStandardMaterial
    Pot_Plant: THREE.MeshStandardMaterial
    Aglaonema_Leaf: THREE.MeshStandardMaterial
    Spray_Bottle: THREE.MeshStandardMaterial
    PC_Tower_and_Mouse: THREE.MeshStandardMaterial
    PC_Monitor_amd_Keyboard: THREE.MeshStandardMaterial
    ['2_Door_Filing_Container']: THREE.MeshStandardMaterial
    Pencil: THREE.MeshStandardMaterial
    Clipboard: THREE.MeshStandardMaterial
    ['4_Door_Filing_Container']: THREE.MeshStandardMaterial
    Calculator: THREE.MeshStandardMaterial
    VHS_Tape: THREE.MeshStandardMaterial
    Blank_Floppy_Disk: THREE.MeshStandardMaterial
    Doom_Floppy_Disk: THREE.MeshStandardMaterial
    Desk: THREE.MeshStandardMaterial
    Desk_Legs: THREE.MeshStandardMaterial
    Cubicle_Wall: THREE.MeshStandardMaterial
    Cubicle_Trim: THREE.MeshStandardMaterial
    Folder: THREE.MeshStandardMaterial
    Stack_of_Papers: THREE.MeshStandardMaterial
    Corkboard: THREE.MeshStandardMaterial
    Pin_Board: THREE.MeshStandardMaterial
    Rubiks_Cube: THREE.MeshStandardMaterial
    Nintendo_Power_Volume_11: THREE.MeshStandardMaterial
    Nirvana_Calendar: THREE.MeshStandardMaterial
    Blade_Runner_Poster: THREE.MeshStandardMaterial
    Coffee_Cup: THREE.MeshStandardMaterial
    Steam: THREE.MeshStandardMaterial
    Terminator_Poster: THREE.MeshStandardMaterial
    Panasonic_VHS_TV: THREE.MeshStandardMaterial
    Nintendo_64: THREE.MeshStandardMaterial
    carpet: THREE.MeshStandardMaterial
    Power_Strip: THREE.MeshStandardMaterial
    Mesh_Basket: THREE.MeshStandardMaterial
    Speed_VHS: THREE.MeshStandardMaterial
    Super_Mario_64_Cartridge: THREE.MeshStandardMaterial
    Swingline_Stapler: THREE.MeshStandardMaterial
    Business_Card_1: THREE.MeshStandardMaterial
    Name_Plate: THREE.MeshStandardMaterial
    Fallout_2_Game_Box_256x256: THREE.MeshStandardMaterial
    Half_Life_Game_Box_256x256: THREE.MeshStandardMaterial
    Speed_Bus_Schedule: THREE.MeshStandardMaterial
    NEWS: THREE.MeshStandardMaterial
    Newspaper: THREE.MeshStandardMaterial
    Notepad: THREE.MeshStandardMaterial
    Feather: THREE.MeshStandardMaterial
    Umbrella_Corp_Key_Card: THREE.MeshStandardMaterial
    Origami_Unicorn: THREE.MeshStandardMaterial
    FF7_Poster_256x256: THREE.MeshStandardMaterial
    Screen_Emission: THREE.MeshStandardMaterial
    Zeldas_Letter: THREE.MeshStandardMaterial
  }
}

export const  Model = (props: JSX.IntrinsicElements['group']) => {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials } = useGLTF('/scene.gltf') as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[6.19, 78.28, -97.75]} rotation={[-1.48, -0.02, -1.74]} scale={[19.38, 19.38, 19.38]}>
            <mesh
              geometry={nodes['Phonehandle_Panasonic_KX-T7420_0'].geometry}
              material={nodes['Phonehandle_Panasonic_KX-T7420_0'].material}
            />
          </group>
          <group position={[11.19, 76.23, -97.2]} rotation={[-Math.PI / 2, 0, -1.75]} scale={[8, 8, 8]}>
            <mesh
              geometry={nodes['Body_Panasonic_KX-T7420_0'].geometry}
              material={nodes['Body_Panasonic_KX-T7420_0'].material}
            />
          </group>
          <group position={[1.97, 9.12, -7.07]} rotation={[-Math.PI, 0.61, 1.92]} scale={[-8.11, 8.11, 3.08]}>
            <mesh geometry={nodes.Wheels_Office_Chair_0.geometry} material={nodes.Wheels_Office_Chair_0.material} />
          </group>
          <group position={[2.18, 37.14, -6.92]} rotation={[-Math.PI / 2, 0, -0.61]} scale={[9.78, 9.78, 9.78]}>
            <mesh geometry={nodes.Piston_Office_Chair_0.geometry} material={nodes.Piston_Office_Chair_0.material} />
          </group>
          <group position={[-1.06, 46.88, -9.19]} rotation={[-Math.PI / 2, 0, -Math.PI / 9]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Bottom_Cushion_Office_Chair_0.geometry}
              material={nodes.Bottom_Cushion_Office_Chair_0.material}
            />
          </group>
          <group position={[21.32, 82.07, 6.48]} rotation={[-2.99, -0.95, -1.19]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Back_Cushion_Office_Chair_0.geometry}
              material={nodes.Back_Cushion_Office_Chair_0.material}
            />
          </group>
          <group position={[17.45, 47.56, 3.76]} rotation={[-Math.PI / 2, 0, -0.61]} scale={[0.92, 0.92, 0.92]}>
            <mesh geometry={nodes.hinge_Office_Chair_0.geometry} material={nodes.hinge_Office_Chair_0.material} />
          </group>
          <group position={[-73.7, 77.14, 43.39]} rotation={[-Math.PI / 2, 0, -2.36]} scale={[6.58, 6.42, 5.07]}>
            <mesh geometry={nodes.Controller_N64_Controller_0.geometry} material={materials.N64_Controller} />
          </group>
          <group position={[-107.08, 5.75, 3.22]} rotation={[-Math.PI / 2, 0, 0]} scale={[10, 10, 10]}>
            <mesh
              geometry={nodes.Power_Plugs_Power_Cable_0.geometry}
              material={nodes.Power_Plugs_Power_Cable_0.material}
            />
          </group>
          <group position={[-103.43, 41.24, -14.32]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Power_Cables_Power_Cable_0.geometry}
              material={nodes.Power_Cables_Power_Cable_0.material}
            />
          </group>
          <group position={[-103.43, 41.24, -14.32]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.Extension_Cable__0.geometry} material={materials.Extension_Cable__0} />
          </group>
          <group position={[-108.09, 138.5, 0]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[8.4, 1.4, 7]}>
            <mesh
              geometry={nodes.Handbook_for_the_Recently_Deceased_Handbook_for_the_Recently_Deceased_0.geometry}
              material={materials.Handbook_for_the_Recently_Deceased}
            />
          </group>
          <group position={[98.75, 9.71, -81.58]} rotation={[-0.05, 0.19, 0.97]} scale={[8.4, 1.4, 7]}>
            <mesh geometry={nodes.Necronomicon_Necronomicon_0.geometry} material={materials.Necronomicon} />
          </group>
          <group position={[-108.71, 135.48, -14.51]} rotation={[-Math.PI / 2, 0, 0]} scale={[8.65, 1.91, 11.75]}>
            <mesh geometry={nodes.Binders_Binders_0.geometry} material={materials.Binders} />
          </group>
          <group position={[-79.5, 112.22, -71.83]} rotation={[0, Math.PI / 4, -2.01]} scale={[4.73, 4.73, 4.73]}>
            <mesh geometry={nodes.Sticky_Notes_Stick_Notes_0.geometry} material={materials.Stick_Notes} />
          </group>
          <group position={[-110.48, 128.35, 31.76]} rotation={[-1.92, -Math.PI / 2, 0]} scale={[7.22, 7.22, 7.22]}>
            <mesh geometry={nodes.CD_CD_Case_0.geometry} material={materials.CD_Case} />
            <mesh geometry={nodes.CD_CD_0.geometry} material={materials.material} />
          </group>
          <group position={[-109.3, 129.36, 31.86]} rotation={[Math.PI, -1.4, -1.22]} scale={[7.22, 7.22, 7.22]}>
            <mesh geometry={nodes.Nevermind_CD_Nevermind_CD_0.geometry} material={materials.Nevermind_CD} />
          </group>
          <group position={[-109.28, 130.34, 32.16]} rotation={[0, -1.22, 1.92]} scale={[7.22, 7.22, 7.22]}>
            <mesh geometry={nodes.Ten_CD_Ten_CD_0.geometry} material={materials.Ten_CD} />
          </group>
          <group position={[-108.85, 131.36, 33.22]} rotation={[Math.PI, -1.49, -1.22]} scale={[7.22, 7.22, 7.22]}>
            <mesh
              geometry={nodes.Definitely_Maybe_CD_Definitely_Maybe_CD_0.geometry}
              material={materials.Definitely_Maybe_CD}
            />
          </group>
          <group position={[-109.28, 132.39, 32.16]} rotation={[0, -1.57, 1.92]} scale={[7.22, 7.22, 7.22]}>
            <mesh geometry={nodes.Astro_Lounge_CD_Astro_Lounge_CD_0.geometry} material={materials.Astro_Lounge_CD} />
          </group>
          <group position={[-108.09, 138.5, 13.44]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[8.4, 1.4, 7]}>
            <mesh
              geometry={nodes.Handbook_for_the_Recently_Deceased001_Material_0.geometry}
              material={materials.Material}
            />
          </group>
          <group position={[-73.59, 75.01, -8.97]} rotation={[-Math.PI / 2, 0, 1.83]} scale={[4.45, 4.45, 4.45]}>
            <mesh geometry={nodes.Burger_Burger_0.geometry} material={materials.Burger} />
          </group>
          <group position={[-103.41, 81.14, -18.21]} rotation={[-Math.PI, 1.31, Math.PI]} scale={[37.88, 37.88, 37.88]}>
            <mesh geometry={nodes.Burger_Bag_Bag_0.geometry} material={materials.material_17} />
          </group>
          <group position={[-73.59, 74.96, -8.97]} rotation={[-Math.PI / 2, 0, 1.83]} scale={[12.45, 12.45, 12.45]}>
            <mesh geometry={nodes.Wrapper_Wrapper_0.geometry} material={materials.Wrapper} />
          </group>
          <group position={[-33.06, 26.25, -82.06]} rotation={[-0.26, Math.PI / 2, 0]} scale={[6, 6, 6]}>
            <mesh geometry={nodes.Y2K_Sticker_y2k_Sticker_0.geometry} material={materials.y2k_Sticker} />
          </group>
          <group position={[93.66, 106.17, -114.38]} scale={50}>
            <mesh geometry={nodes.Hang_In_There_Poster_Hang_In_There_0.geometry} material={materials.Hang_In_There} />
          </group>
          <group position={[-0.37, 12.09, -91.61]} rotation={[Math.PI, 0.44, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.The_Box_The_box_0.geometry} material={materials.The_box} />
          </group>
          <group position={[52.95, 137.72, -94.98]} rotation={[-Math.PI / 2, 0, 0.44]} scale={19.5}>
            <mesh geometry={nodes.Potted_Plant_Pot_Plant_0.geometry} material={materials.Pot_Plant} />
            <mesh geometry={nodes.Potted_Plant_Aglaonema_Leaf_0.geometry} material={materials.Aglaonema_Leaf} />
          </group>
          <group
            position={[56.98, 128.55, -74.32]}
            rotation={[-Math.PI / 2, 0, Math.PI / 4]}
            scale={[2.24, 2.24, 2.24]}>
            <mesh geometry={nodes.Bottle_Spray_Bottle_0.geometry} material={materials.Spray_Bottle} />
          </group>
          <group position={[-43.46, 22.5, -83.96]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
            <mesh
              geometry={nodes.PC_Tower_PC_Tower_and_Mouse_0.geometry}
              material={nodes.PC_Tower_PC_Tower_and_Mouse_0.material}
            />
          </group>
          <group position={[-40.76, 75.54, -75.16]} rotation={[-Math.PI / 2, 0, -0.96]} scale={[30.89, 30.89, 30.89]}>
            <mesh
              geometry={nodes.mouse_PC_Tower_and_Mouse_0.geometry}
              material={nodes.mouse_PC_Tower_and_Mouse_0.material}
            />
          </group>
          <group position={[-67.84, 76.21, -55.38]} rotation={[-Math.PI / 2, 0, 0.88]} scale={[39.49, 39.49, 39.49]}>
            <mesh
              geometry={nodes.Keyboard_PC_Monitor_amd_Keyboard_0.geometry}
              material={nodes.Keyboard_PC_Monitor_amd_Keyboard_0.material}
            />
          </group>
          <group
            position={[-90.03, 99.75, -86.59]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 4]}
            scale={[15.89, 17.78, 17.78]}>
            <mesh
              geometry={nodes.Computer_Monitor_PC_Monitor_amd_Keyboard_0.geometry}
              material={nodes.Computer_Monitor_PC_Monitor_amd_Keyboard_0.material}
            />
          </group>
          <group position={[-86.3, 35.99, 87.74]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes['2_Drawer_Filing_Cabinet_2_Door_Filing_Container_0'].geometry}
              material={materials['2_Door_Filing_Container']}
            />
          </group>
          <group position={[-78.25, 75.17, 16.65]} rotation={[-Math.PI / 2, 0, -0.26]} scale={0.41}>
            <mesh geometry={nodes.Pencil_Pencil_0.geometry} material={nodes.Pencil_Pencil_0.material} />
          </group>
          <group position={[-81.51, 75.04, -74.84]} rotation={[-Math.PI / 2, 0, -1.13]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.Pencil_2_Pencil_0.geometry} material={nodes.Pencil_2_Pencil_0.material} />
          </group>
          <group position={[99.69, 0.32, -23.57]} rotation={[-Math.PI / 2, 0, 0.7]} scale={[8.03, 10.33, 10.33]}>
            <mesh geometry={nodes.Clipboard_Clipboard_0.geometry} material={materials.Clipboard} />
          </group>
          <group position={[47.55, 37.98, -57.33]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100}>
            <mesh
              geometry={nodes.Drawer_4_Door_Filing_Container_0.geometry}
              material={nodes.Drawer_4_Door_Filing_Container_0.material}
            />
          </group>
          <group position={[-44.3, 45.6, -86.92]} rotation={[-Math.PI / 2, 0, -Math.PI / 6]} scale={[3.28, 3.28, 3.28]}>
            <mesh geometry={nodes.Calculator_Calculator_0.geometry} material={materials.Calculator} />
          </group>
          <group position={[-83.31, 125.47, 81.68]} rotation={[-Math.PI / 2, 0, -2.97]} scale={[10.11, 10.11, 10.11]}>
            <mesh geometry={nodes.VHS_VHS_Tape_0.geometry} material={materials.VHS_Tape} />
          </group>
          <group position={[-102.49, 74.92, -51.61]} rotation={[-Math.PI / 2, 0, 0.26]} scale={[17.79, 17.79, 17.79]}>
            <mesh
              geometry={nodes.Blank_Floppy_Disk_Blank_Floppy_Disk_0.geometry}
              material={materials.Blank_Floppy_Disk}
            />
          </group>
          <group position={[-41.91, 45.02, -73.76]} rotation={[-Math.PI / 2, 0, -1.92]} scale={[17.79, 17.79, 17.79]}>
            <mesh geometry={nodes.Doom_Floppy_Disk_Doom_Floppy_Disk_0.geometry} material={materials.Doom_Floppy_Disk} />
          </group>
          <group position={[-57.79, 59.98, -11.78]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
            <mesh geometry={nodes.Cubicle_Desk_Desk_0.geometry} material={nodes.Cubicle_Desk_Desk_0.material} />
            <mesh geometry={nodes.Cubicle_Desk_Desk_Legs_0.geometry} material={materials.Desk_Legs} />
          </group>
          <group position={[47.57, 56.7, -87.94]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100}>
            <mesh
              geometry={nodes['4_Drawer_Filing_Cabinet_4_Door_Filing_Container_0'].geometry}
              material={nodes['4_Drawer_Filing_Cabinet_4_Door_Filing_Container_0'].material}
            />
          </group>
          <group position={[-16.93, 84.4, -6.54]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
            <mesh geometry={nodes.Cubicle_Cubicle_Wall_0.geometry} material={materials.Cubicle_Wall} />
          </group>
          <group position={[-16.38, 84.9, -4.59]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
            <mesh geometry={nodes.Cubicle_Trim_Cubicle_Trim_0.geometry} material={materials.Cubicle_Trim} />
          </group>
          <group position={[-79.87, 0.57, 47]} rotation={[-Math.PI / 2, 0, -0.93]} scale={[21.4, 21.4, 21.4]}>
            <mesh geometry={nodes.Folder_Folder_0.geometry} material={nodes.Folder_Folder_0.material} />
          </group>
          <group
            position={[-30.81, 47.55, -18.75]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={[10.8, 13.97, 10.59]}>
            <mesh
              geometry={nodes.Stack_of_Papers_Stack_of_Papers_0.geometry}
              material={nodes.Stack_of_Papers_Stack_of_Papers_0.material}
            />
          </group>
          <group position={[48.56, 30.16, -68.13]} rotation={[-Math.PI / 2, 0, 0]} scale={[10.8, 13.97, 10.59]}>
            <mesh
              geometry={nodes.Secret_File_Stack_of_Papers_0.geometry}
              material={nodes.Secret_File_Stack_of_Papers_0.material}
            />
          </group>
          <group position={[49.81, 42.01, -63.39]} rotation={[-Math.PI, 0, -1.6]} scale={[21.4, 21.4, 21.4]}>
            <mesh geometry={nodes.Cabinet_Folder_Folder_0.geometry} material={nodes.Cabinet_Folder_Folder_0.material} />
          </group>
          <group position={[-17.88, 125.63, -114.36]} rotation={[-Math.PI / 2, 0, 0]} scale={4}>
            <mesh geometry={nodes.Corkboard_Corkboard_0.geometry} material={materials.Corkboard} />
          </group>
          <group position={[-38.28, 131.35, -37.14]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[-3.2, 3.2, 3.2]}>
            <mesh geometry={nodes.Pin_Pin_Board_0.geometry} material={nodes.Pin_Pin_Board_0.material} />
          </group>
          <group position={[6.13, 129.88, -113.8]} rotation={[0, Math.PI / 2, 0]} scale={[12.56, 12.56, 12.56]}>
            <mesh
              geometry={nodes.Sticky_Note_1_Pin_Board_0.geometry}
              material={nodes.Sticky_Note_1_Pin_Board_0.material}
            />
          </group>
          <group position={[-13.03, 111.5, -113.31]} rotation={[0, Math.PI / 2, 0]} scale={[12.56, 12.56, 12.56]}>
            <mesh
              geometry={nodes.Sticky_Note_2_Pin_Board_0.geometry}
              material={nodes.Sticky_Note_2_Pin_Board_0.material}
            />
          </group>
          <group position={[-100.92, 77.56, -36.81]} rotation={[-Math.PI / 2, 0, -0.44]} scale={4.57}>
            <mesh geometry={nodes.Rubiks_Cube_Rubiks_Cube_0.geometry} material={materials.Rubiks_Cube} />
          </group>
          <group position={[5.88, 76.21, -70.89]} rotation={[-Math.PI / 2, 0, -2.09]} scale={[19.17, 19.17, 1.55]}>
            <mesh
              geometry={nodes.Nintendo_Power_Vol_11_Nintendo_Power_Volume_11_0.geometry}
              material={nodes.Nintendo_Power_Vol_11_Nintendo_Power_Volume_11_0.material}
            />
          </group>
          <group position={[-3.25, 76.36, -69.66]} rotation={[-Math.PI / 2, 0, -1.75]} scale={[19.17, 19.17, 1.55]}>
            <mesh
              geometry={nodes.Nintendo_Power_Vol_66_Nintendo_Power_Volume_11_0.geometry}
              material={nodes.Nintendo_Power_Vol_66_Nintendo_Power_Volume_11_0.material}
            />
          </group>
          <group
            position={[116.73, 112.67, -25.75]}
            rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
            scale={[35.37, 16.98, 16.98]}>
            <mesh geometry={nodes.Nirvana_Calendar_Nirvana_Calendar_0.geometry} material={materials.Nirvana_Calendar} />
          </group>
          <group position={[116.67, 97.53, -76.63]} rotation={[0.07, Math.PI / 2, 0]} scale={[104, 104, 0]}>
            <mesh
              geometry={nodes.Blade_Runner_Poster_Blade_Runner_Poster_0.geometry}
              material={materials.Blade_Runner_Poster}
            />
          </group>
          <group position={[-89.54, 78.57, -29.41]} rotation={[-Math.PI / 2, 0, 0]} scale={[5, 5, 5]}>
            <mesh geometry={nodes.Coffee_Cup_Coffee_Cup_0.geometry} material={materials.Coffee_Cup} />
          </group>
          <group position={[-89.46, 86.03, -29.7]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[6.73, 5.02, 6.73]}>
            <mesh geometry={nodes.Steam_Steam_0.geometry} material={materials.Steam} />
          </group>
          <group position={[61.22, 100.98, 117.2]} rotation={[-Math.PI, 0, -3.12]} scale={[80, 80, 0]}>
            <mesh
              geometry={nodes.Terminator_Poster_Terminator_Poster_0.geometry}
              material={materials.Terminator_Poster}
            />
          </group>
          <group position={[-87.03, 98.64, 89.16]} rotation={[-Math.PI / 2, 0, 0.61]} scale={[24.7, 24.7, 24.7]}>
            <mesh
              geometry={nodes.Panasonic_VHS_TV_Panasonic_VHS_TV__0.geometry}
              material={materials.Panasonic_VHS_TV}
            />
          </group>
          <group position={[-96.55, 77.3, 45.69]} rotation={[Math.PI / 2, 0, 2.97]} scale={[2.58, 2.38, 1.68]}>
            <mesh geometry={nodes.N64_Console_Nintendo_64_0.geometry} material={materials.Nintendo_64} />
          </group>
          <group position={[0, 0, 3.83]} rotation={[-Math.PI / 2, 0, 0]} scale={240}>
            <mesh geometry={nodes.Carpetimg_carpet_0.geometry} material={materials.carpet} />
          </group>
          <group position={[-107.97, 2.24, -3.59]} rotation={[Math.PI / 2, 0, 1.75]} scale={[-18, 3.6, 2.24]}>
            <mesh geometry={nodes.Outlet_Power_Strip_0.geometry} material={materials.Power_Strip} />
          </group>
          <group position={[92.21, 21.87, -78.12]} rotation={[-Math.PI / 2, 0, 0]} scale={[17.53, 17.53, 17.53]}>
            <mesh geometry={nodes.Trash_Cam_Mesh_Basket_0.geometry} material={materials.Mesh_Basket} />
          </group>
          <group position={[-83.32, 127.99, 82.69]} rotation={[-Math.PI / 2, 0, 2.92]} scale={10.11}>
            <mesh geometry={nodes.Speed_VHS_Speed_VHS_0.geometry} material={materials.Speed_VHS} />
          </group>
          <group position={[-102.19, 80.87, 46.8]} rotation={[-Math.PI, 1.4, Math.PI / 2]} scale={[3.75, 5.8, 0.9]}>
            <mesh
              geometry={nodes.Super_Mario_64_Cartridge_Super_Mario_64_Cartridge_0.geometry}
              material={materials.Super_Mario_64_Cartridge}
            />
          </group>
          <group position={[-110.25, 126.25, -2.48]} rotation={[-Math.PI / 2, 0, 0]} scale={[8.97, 44.47, 1.67]}>
            <mesh geometry={nodes.Shelf_Desk_0.geometry} material={nodes.Shelf_Desk_0.material} />
          </group>
          <group position={[-56.12, 75.56, -93.7]} rotation={[-Math.PI / 2, 0, 0.87]} scale={[6.65, 1.11, 0.66]}>
            <mesh geometry={nodes.Stapler_Swingline_Stapler_0.geometry} material={materials.Swingline_Stapler} />
          </group>
          <group position={[-3, 75.27, -94.9]} rotation={[-Math.PI / 2, 0, Math.PI / 9]} scale={[3.07, 1.92, 1.92]}>
            <mesh geometry={nodes.Tyler_Durden_Card_Business_Card_1_0.geometry} material={materials.Business_Card_1} />
          </group>
          <group position={[120.6, 156.22, -24.97]} rotation={[0, Math.PI / 2, 0]} scale={[9.52, 9.52, 9.52]}>
            <mesh geometry={nodes.Name_Plate_Name_Plate_0.geometry} material={materials.Name_Plate} />
          </group>
          <group position={[-119.23, 107.38, 23.18]} rotation={[-Math.PI, 0, Math.PI]} scale={[12.56, 12.56, 12.56]}>
            <mesh
              geometry={nodes.Sticky_Note_1001_Pin_Board_0.geometry}
              material={nodes.Sticky_Note_1001_Pin_Board_0.material}
            />
          </group>
          <group position={[-105.68, 136.8, -29.72]} rotation={[Math.PI, 1.31, -Math.PI]} scale={[24, 24, 24]}>
            <mesh
              geometry={nodes.Fallout_2_Game_Box_256x256_Fallout_2_Game_Box_256x256_0.geometry}
              material={materials.Fallout_2_Game_Box_256x256}
            />
          </group>
          <group position={[2.44, 173.61, 3.34]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Half_Life_Game_Box_256x256_Half_Life_Game_Box_256x256_0.geometry}
              material={materials.Half_Life_Game_Box_256x256}
            />
          </group>
          <group position={[-71.68, 124.5, 96.57]} rotation={[-Math.PI / 2, 0, -2.97]} scale={[30.25, 30.25, 30.25]}>
            <mesh
              geometry={nodes.Speed_Bus_Schedule_Speed_Bus_Schedule_0.geometry}
              material={materials.Speed_Bus_Schedule}
            />
          </group>
          <group position={[-114.56, 105.62, -49.38]} rotation={[0, Math.PI / 2, 0]} scale={28}>
            <mesh geometry={nodes.NEWS_NEWS_0.geometry} material={materials.NEWS} />
          </group>
          <group position={[90.84, 1.07, -39.38]} rotation={[-Math.PI / 2, 0, -Math.PI / 9]} scale={[52, 52, 52]}>
            <mesh geometry={nodes.Newspaper_Newspaper_0.geometry} material={materials.Newspaper} />
          </group>
          <group position={[40.66, 114.44, -74.81]} rotation={[-Math.PI / 2, 0, -Math.PI / 9]} scale={[12, 10, 10]}>
            <mesh geometry={nodes.Notepad__Notepad__0.geometry} material={materials.Notepad} />
          </group>
          <group position={[46.95, 113.6, -74.51]} rotation={[-Math.PI / 2, 0, -0.7]} scale={[8, 8, 8]}>
            <mesh geometry={nodes.Feather_Feather_0.geometry} material={materials.Feather} />
          </group>
          <group position={[40.7, 30.66, -58.76]} rotation={[-Math.PI / 2, 0, -0.96]} scale={10}>
            <mesh
              geometry={nodes.Umbrella_Corp_Key_Card_Umbrella_Corp_Key_Card_0.geometry}
              material={materials.Umbrella_Corp_Key_Card}
            />
          </group>
          <group position={[-90.22, 128.5, 67.79]} rotation={[-Math.PI, 0.44, Math.PI / 2]} scale={[1.2, 1.2, 1.2]}>
            <mesh geometry={nodes.Unicorn_Origami_Unicorn_0.geometry} material={materials.Origami_Unicorn} />
          </group>
          <group position={[-8.81, 91.17, 116.98]} rotation={[-Math.PI, 0, -Math.PI]} scale={80}>
            <mesh
              geometry={nodes.FF7_Poster_256x256_FF7_Poster_256x256_0.geometry}
              material={materials.FF7_Poster_256x256}
            />
          </group>
          <group position={[-77.69, 107.12, -74.44]} rotation={[0, Math.PI / 4, 0]} scale={[15.01, 15.01, 15.01]}>
            <mesh geometry={nodes.Glowing_Screen_Screen_Emission_0.geometry} material={materials.Screen_Emission} />
          </group>
          <group position={[-118.1, 102.66, 52.57]} rotation={[-1.48, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.Zeldas_Letter_Zeldas_Letter_0.geometry} material={materials.Zeldas_Letter} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
